### ISSUE TITLE
Problem with the installation of the module

### ISSUE THREAD

**Issue by jhuriez** [limegrow/ingenico-ogone-prestashop-payments#2]
Hi,

I tried to install the module, but i have this error : **This file does not appear to be a valid module zip file**
My prestashop version is 1.7.5.2

![image](https://user-images.githubusercontent.com/3176175/117254243-780e1800-ae48-11eb-997c-86dd1030b760.png)

And i have followed this instruction : 
https://epayments-support.ingenico.com/en/integration-solutions/plugins/prestashop

**Comment by raidoa** [comment]
Hi @jeckyl,

Sorry for that. We'll have a look into the issue and to the possibility of making it smoother. :)

**Comment by KleiDav** [comment]
hello @raidoa 

I have the same problem as @jhuriez 
But the solution advised by @jeckyl does not work for me.
Created a new zip file with ingenico_epayments folder in it, then all the files
But still same error

**Comment by olegisk** [comment]
Hello, @KleiDav @jeckyl 
We are working very hard on new version with improvements and bugfixes.
I've made manual how to install the module. You can read [README.md](https://github.com/limegrow/ingenico-ogone-prestashop-payments/blob/master/README.md)

@KleiDav Please contact me oleg@iskusnyh.pro. I will provide you module where v1.7.7 support was added

**Comment by ethercreation** [comment]
Hello,

We have version 1.7.6.1 and have the same installation error despite going through the process.

Do you have a functional zip to send me?

Regards,

**Comment by olegisk** [comment]
@ethercreation Please contact me oleg@iskusnyh.pro. I will provide you module. It's release candidate, not final release

**Comment by d33x** [comment]
Hello @KleiDav and @ethercreation 

I had this error too, renaming the file as reported by @jeckyl , there is still the error BUT the module installs anyway. Check the installed modules

**Comment by olegisk** [comment]
You can download and install module from there https://disk.yandex.ru/d/afO-XAxtLkh7mg

**Comment by KleiDav** [comment]
Hello Oleg

Nothing is working for me.

Downloaded the latest version from GitHub - limegrow/ingenico-ogone-prestashop-payments: Prestashop module for Ingenico ePayments (Ogone) ( https://github.com/limegrow/ingenico-ogone-prestashop-payments )
Does not install

Downloaded from your link, does not install

Unzipped and recreated a zip as "ingenico_epayments.zip"; dos not install

—
David

On June 12, 2021 at 10:14 AM, Oleg Iskusnyh ***@***.***) wrote:
Closed #2 ( https://github.com/limegrow/ingenico-ogone-prestashop-payments/issues/2 ).
