### ISSUE TITLE
Refunds from PrestaShop BO --> displayBackOfficeOrderActions is deprecated since 1.7.7

### ISSUE THREAD

**Issue by d33x** [limegrow/ingenico-ogone-prestashop-payments#3]
Hello,

Is it possible to provide the refund directly from the PrestaShop back office as the PayPal module allows?

That would be a great improvement!

**Comment by olegisk** [comment]
@d33x Hello. This feature is already exists.
![Screenshot12344](https://user-images.githubusercontent.com/871275/119110888-5b770000-ba44-11eb-8e84-68675fd83c61.png)

**Comment by d33x** [comment]
@olegisk Oh great news! It does work in 1.7.6 but not in 1.7.7 since they reworked the BO command pages (see : https://build.prestashop.com/news/prestashop-1-7-7-0-available/ and https://build.prestashop.com/news/the-new-order-pages-in-prestaShop-1-7-7/ )
The hook displayBackOfficeOrderActions is deprecated since 1.7.7, you have to use the hook actionGetAdminOrderButtons (new hook) (see: https://devdocs.prestashop.com/1.7/modules/concepts/hooks/list-of-hooks/ )
![21-05-2021 14-54-39](https://user-images.githubusercontent.com/76649472/119140532-8b260800-ba44-11eb-9e1c-10fb6d38e362.png)

The advantage of PayPal is that you can make the refund directly from the PrestaShop refund page and generate the credit slip at the same time

**Comment by olegisk** [comment]
@d33x Yes, we know about PS v1.7.7 changes and we are working on that.
If you need then i can send you module for v1.7.7

**Comment by d33x** [comment]
@olegisk Thank you for your answer.

I would like to receive the module for 1.7.7, I guess it is a beta version?
If so, do you have any idea when it will be released?

**Comment by d33x** [comment]
Thanks!
