### ISSUE TITLE
"Send an e-mail when refund has been failed." doesn't work

### ISSUE THREAD

**Issue by d33x** [limegrow/ingenico-ogone-prestashop-payments#4]
Hello,

I have disabled the email option when the refund is refused/failed but I still received an email.
![21-05-2021 09-43-38](https://user-images.githubusercontent.com/76649472/119101397-3caf4400-ba19-11eb-8555-55a5a116dfff.png)

At the same time, the content of the email is empty. How can I change the content, it does not appear in the "Email translations on PrestaShop"?

Thanks

**Comment by d33x** [comment]
Looking at the module code, I see a function for the email in case of failed refund for the customer and a function for the merchant. Which function is handled via this option?

I was both the customer and the merchant in this case.

**Comment by olegisk** [comment]
@d33x Please attach screenshots of email messages

**Comment by d33x** [comment]
PrestaShop 1.7.7
![21-05-2021 14-54-39](https://user-images.githubusercontent.com/76649472/119141147-359e2b00-ba45-11eb-9ce1-bce3dba9e4fb.png)

**Comment by olegisk** [comment]
@d33x Can you write how to reproduce this bug "step by step" please?

**Comment by d33x** [comment]
@olegisk 

I still have the problem. Step by step:

1. Do not activate the "Send an e-mail when refund has been failed." option.
2. Make a refund on an order
3. Not having enough funds on Ingenico to refund
4. Wait a few days (7 days for me) for the refund to be refused

An email is then sent
