### ISSUE TITLE
Bugs in v3, unable to install v4

### ISSUE THREAD

**Issue by PierreG89** [limegrow/ingenico-ogone-prestashop-payments#6]
Hello,

On v3, I only added 1 payment method : "Bancontact", and we can see two payments methods... I think the 2 redirects to Bancontact option but would be better to show only Bancontact... (maybe it is ok in v4, but can't check it as I can't install it, I'm explaining later).

![Ingenico Debug 0](https://user-images.githubusercontent.com/5750914/119383530-b9fde180-bcc3-11eb-99f5-f178651071df.PNG)

I can make the Bancontact payment on test environment but the return seems wrong... Again that maybe corrected in v4 but can't check it...

![Ingenico Debug 1-1](https://user-images.githubusercontent.com/5750914/119384207-a1da9200-bcc4-11eb-9380-7abfd5c51b2b.png)

Then I tried to install v4...impossible. Here are screenshots :

![Ingenico Debug 2](https://user-images.githubusercontent.com/5750914/119383959-4b6d5380-bcc4-11eb-9829-13b7d5d6a302.PNG)
![Ingenico Debug 3](https://user-images.githubusercontent.com/5750914/119383967-4e684400-bcc4-11eb-933c-00916d6764ce.PNG)

After that my admin. stopped working completely, I had to delete "ingenico_epayments" folder to make my admin. working again:

![Ingenico Debug 4](https://user-images.githubusercontent.com/5750914/119384068-6fc93000-bcc4-11eb-9523-55970d09d301.PNG)

I've tried to reinstall v3 over this, but it was labelled v4 for a moment, then I try to "reset" mobule. Reset seems not working but module is labelled again.

Thanks for help, as Bancontact would my the only payment method for this shop, I can't use ingenico.

**Comment by olegisk** [comment]
@PierreG89 Sorry, we had problems with /vendor directory and composer  dependencies. But we will solve this in the feature.
Btw, please make installation package again from start, because i've just replaced /vendor directory to another. I believe it should work.

**Comment by PierreG89** [comment]
Thanks for fast answer. I tried new package, installation is working now. But I still have this error on the return:

![Ingenico Debug 5](https://user-images.githubusercontent.com/5750914/119389464-f3d2e600-bccb-11eb-8c0a-6469deadf7f3.PNG)

**Comment by olegisk** [comment]
@olegisk It seems something was configured wrong. There's SHASIGN parameter is missing (and other parameters too). I guess something wrong was configured in Ingenico BO. 
Can you contact me oleg@iskusnyh.pro? I'm ready to help you.

**Comment by PierreG89** [comment]
I followed that guide https://epayments-support.ingenico.com/en/integration-solutions/plugins/prestashop
I don't want to bother you if the error is not by your side..

**Comment by PierreG89** [comment]
So weird, payement is accepted, so the return seems working but still ends with the above error 
![image](https://user-images.githubusercontent.com/5750914/119397044-ede20280-bcd5-11eb-8e82-7184541e699e.png)
All I changed is to tick "POST" method at accepted webhook (nothing was checked betwen GET or POST...).

**Comment by PierreG89** [comment]
That option was not in any guide..."I want to receive the transaction parameters back in the urls when redirecting.".
I am redirected to the site now, but I don't understand why POSTed parameters needed to be in the url as a GET... Because the transaction was validated, even without the GET parameters in the URL...

![image](https://user-images.githubusercontent.com/5750914/119404635-5df58600-bce0-11eb-81ca-2639e8ef4c0b.png)

**Comment by olegisk** [comment]
@PierreG89 No problem, if you want then i can send you video how to configure Ingenico BO.
Regarding this error. Probably, DirectLink credentials were invalid or STATUS field was missing

**Comment by PierreG89** [comment]
STATUS is in DirectLink and eCommerce parameters... Don't understand. I emailed you to get this video but perhaps it maybe very helpful to publish it here as the main guide is not very complete...

**Comment by olegisk** [comment]
@PierreG89 I've sent you. I hope it will help you

**Comment by PierreG89** [comment]
Thanks I've seen it. ALL the parameters were added but it didn't work... All that was missing is...**a new API user only**...Now it seems to work. Thanks again.
