### ISSUE TITLE
Issue with v3 and v4 on Prestashop 1.7.7.4

### ISSUE THREAD

**Issue by Prestaplugins** [limegrow/ingenico-ogone-prestashop-payments#7]
Hello,

I'm trying to use the module on Prestashop 1.7.7.4 with Php 7.2, but I always get error on front-end when I try to make the purchase, or in back-end when I enter a new order made using the module (which is created but in "Waiting for ingenico payment" status).

I tried both v3.0.0 and v4.0.0 and the problem is still here.

In front-end :
![image](https://user-images.githubusercontent.com/3033446/120314167-3bb0c900-c2db-11eb-8e3f-6d391c88a28a.png)

In back-end :
![image](https://user-images.githubusercontent.com/3033446/120314230-4ff4c600-c2db-11eb-84cf-ebf60cefeab2.png)

I tried to contact the support using the form included in the module, but I got no answer.

Can you please help me ?

Best regards,

Yann

**Comment by olegisk** [comment]
@Prestaplugins `bcmath` php extension is missing. Please install it.
